#!/bin/bash

# HAProxy Offline Package Preparation Script
# Generated by MoonMesh
# Run this script on a system with internet connection

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log() {
    local color="$1"
    local text="$2"
    case $color in
        red) echo -e "${RED}❌ $text${NC}" ;;
        green) echo -e "${GREEN}✅ $text${NC}" ;;
        yellow) echo -e "${YELLOW}⚠️  $text${NC}" ;;
        cyan) echo -e "${CYAN}🔧 $text${NC}" ;;
        *) echo -e "$text" ;;
    esac
}

echo -e "${CYAN}📦 HAProxy Offline Package Preparation${NC}"
echo "========================================"
echo

# ========================================
# Prepare .deb packages (Ubuntu/Debian)
# ========================================

prepare_deb_packages() {
    log cyan "Preparing .deb packages for Ubuntu/Debian..."
    
    if ! command -v apt-get &> /dev/null; then
        log red "apt-get not found. This section requires Ubuntu/Debian."
        return 1
    fi
    
    # ایجاد دایرکتوری
    mkdir -p haproxy-packages
    cd haproxy-packages
    
    log yellow "Updating package lists..."
    apt-get update -qq
    
    log cyan "Downloading HAProxy and dependencies..."
    
    # دانلود HAProxy
    apt-get download haproxy
    
    # دانلود dependency ها
    DEPS=$(apt-cache depends haproxy | grep "Depends:" | awk '{print $2}' | grep -v "<" | sort -u)
    
    for dep in $DEPS; do
        log cyan "Downloading dependency: $dep"
        apt-get download "$dep" 2>/dev/null || log yellow "Could not download: $dep"
    done
    
    # دانلود پکیج‌های اضافی مفید
    apt-get download libc6 libssl3 libpcre3 2>/dev/null || true
    
    cd ..
    
    log green "✅ .deb packages prepared in 'haproxy-packages' directory"
    log cyan "📋 Package count: $(ls haproxy-packages/*.deb 2>/dev/null | wc -l)"
    echo
}

# ========================================
# Main execution
# ========================================

main() {
    echo "Select preparation method:"
    
    echo "1) Prepare .deb packages"
    read -p "Press Enter to continue..."
    prepare_deb_packages
    
    echo
    log green "🎉 Package preparation completed!"
    echo
    log cyan "📋 Next steps:"
    echo "  1. Copy the prepared directories to your target system"
    echo "  2. Run MoonMesh with HAProxy configuration"
    echo "  3. Choose appropriate offline installation method"
    echo
    log yellow "💡 Prepared directories:"
    [[ -d "haproxy-packages" ]] && echo "  • haproxy-packages/ (.deb files)"
    [[ -d "haproxy-packages-rpm" ]] && echo "  • haproxy-packages-rpm/ (.rpm files)"
    [[ -d "haproxy-binary" ]] && echo "  • haproxy-binary/ (binary file)"
}

# اجرای تابع اصلی
main "$@"
